name: Generate Snake Animation
on:
  schedule: # Run every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Generate Snake (SVG - Light Mode)
        uses: Platane/snk@v3
        with:
          github_user_name: asbinthapa99
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Snake (Multiple Styles)
        uses: Platane/snk@v3
        with:
          github_user_name: asbinthapa99
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#ff6b6b
            dist/neon-snake.svg?color_snake=#00ff41&color_dots=#0d1117,#1f6feb,#58a6ff,#79c0ff,#a5d6ff
            dist/fire-snake.gif?color_snake=#ff4500&color_dots=#2d1b00,#ff6347,#ff8c00,#ffd700,#ffff00
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify files generated
        run: |
          echo "Generated files:"
          ls -lh dist/
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
          commit_message: "Update snake animations [skip ci]"
          keep_history: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: snake-animations
          path: dist/
          retention-days: 30

  notify:
    needs: generate
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check job status
        run: |
          if [ "${{ needs.generate.result }}" == "success" ]; then
            echo "✅ Snake animation generated successfully!"
          else
            echo "❌ Snake animation generation failed!"
            exit 1
          fi
