name: Generate Snake Animation
on:
  schedule: # Run every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch: # Allow manual trigger
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: asbinthapa99
          outputs: dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
